### ISSUE TITLE
Does photondb support write ahead log?

### ISSUE THREAD

**Issue by SGZW** [photondb/photondb#301]
A glance at the code, photondb is not support wal and page store write buffer flushing is asynchronous. So after    page txn commit finished, page store won't ensure modification is durable.  

Currently table's get / put api have lsn args but write buffer isn't aware of the lsn, so write buffer can't know checkpoint_lsn(like innodb) after flushed.

Will photondb support wal in the future and page store be aware of something of lsn ?

**Comment by huachaohuang** [comment]
The current version doesn't have a WAL yet. We plan to add a standalone WAL module in the future. Since users have different use cases for WAL and the tree, we tend to make as few assumptions about the LSN as possible. We try to let advanced users control the interaction (e.g., checkpoint) between the WAL and the tree.

**Comment by SGZW** [comment]
> The current version doesn't have a WAL yet. We plan to add a standalone WAL module in the future. Since users have different use cases for WAL and the tree, we tend to make as few assumptions about the LSN as possible. We try to let advanced users control the interaction (e.g., checkpoint) between the WAL and the tree.

Thanks for explanation. So photondb will support some interfaces like **Mk-Stable** function in **LLAMA**  or some event callback to help advanced user to control checkpoint ?

**Comment by huachaohuang** [comment]
I think that depends on the use case. In the current interface, it is the user's responsibility to assign LSNs to entries. So there should be some kind of contract between the WAL and the tree. For simple use cases, users can assign globally increasing LSNs to entries. And the tree can expose the latest flushed LSN to users. I haven't figured out all the details yet.
